name: todo
description: "A smart todo list app with auto-scheduling and task management."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0-323.0.dev <4.0.0"

dependencies:
  google_generative_ai: ^0.2.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.0
  
  # Core functionality
  intl: ^0.17.0
  shared_preferences: ^2.2.2
  timezone: ^0.9.2  # Downgraded to be compatible with flutter_local_notifications
  
  # Added for timezone support with notifications
  flutter_timezone: ^1.0.8
  
  # UI and animations
  google_fonts: ^4.0.4
  flutter_animate: ^4.1.1+1
  confetti: ^0.7.0
  fl_chart: ^0.64.0
  supercharged: ^2.1.1
  flutter_spinkit: ^5.2.0
  sleek_circular_slider: ^2.0.1
  simple_animations: ^5.0.2  # Added for advanced animations
  
  # Notifications and sensors
  flutter_local_notifications: ^15.1.0+1
  sensors_plus: ^3.0.3
  noise_meter: ^3.2.0
  
  # Device information
  device_info_plus: ^9.0.3
  app_usage: ^2.1.1
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # Additional packages for enhanced functionality
  provider: ^6.1.1
  flutter_slidable: ^3.0.1
  path_provider: ^2.1.2
  uuid: ^4.3.3
  flutter_svg: ^2.0.9
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true